# Proyecto QTranslate LIFIA — Quirk → OpenQASM 3.0 → Ecosistema objetivo

Este cuaderno de pruebas pretende ejecutar una etapa de verificación funcional inicial sobre las traducciones, para ello ejecuta las siguientes subetapas:

1. Descarga de librerías externas necesarias
2. Traduce circuitos de [Quirk](https://algassert.com/quirk) a OpenQASM 3.0.

    Carga de los algoritmos de prueba 15 a partir del JSON algorithms.json y traduccion a OpenQasm (12 preexistentes y 3 generados por nosotros, path /algorithms_qasm)

3. Generación de circuitos visuales en Quirk (path /circuits_quirk)
4. Generación de circuitos visuales en OpenQasm (path /circuits_qasm)

1. Descarga de las librerías necesarias para la funcionalidad

In [ ]:
import sys
import subprocess
import importlib.util

print('Python:', sys.executable)

packages = {
    'qiskit': 'qiskit',
    'matplotlib': 'matplotlib',
    'qiskit_aer': 'qiskit-aer',
    'pylatexenc': 'pylatexenc',
    'qiskit_qasm3_import': 'qiskit-qasm3-import',
    'pandas': 'pandas',
    'pyzx': 'pyzx',
}

detalle_info = ''
paquetes_instalados = 0

for module_name, pip_name in packages.items():
    if importlib.util.find_spec(module_name) is None:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', pip_name])
        estado = 'no existente, se instaló correctamente'
        paquetes_instalados += 1
    else:
        estado = 'existente previamente, no se instaló'

    info = f"{pip_name} - {estado}"
    detalle_info += (', ' if detalle_info else '') + info
    print(f'Paquete: {info}')

print(f'\nCantidad de paquetes instalados en este kernel: {paquetes_instalados}')
print('Paquetes requeridos para la funcionalidad, disponibles actualmente en el kernel.')

Python: c:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\.venv\Scripts\python.exe
Paquete: qiskit - existente previamente, no se instaló
Paquete: matplotlib - existente previamente, no se instaló
Paquete: qiskit-aer - existente previamente, no se instaló
Paquete: pylatexenc - existente previamente, no se instaló
Paquete: qiskit-qasm3-import - existente previamente, no se instaló
Paquete: pandas - existente previamente, no se instaló
Paquete: pyzx - existente previamente, no se instaló

Cantidad de paquetes instalados en este kernel: 0
Paquetes requeridos para la funcionalidad, disponibles actualmente en el kernel.

### Generamos una tabla (MarkDown) por cada algoritmo de prueba que vayamos a ejecutar (path /input/algorithms.json y /input/popular_algorithms.json)

In [ ]:
import json
from pathlib import Path
from IPython.display import display, Markdown
import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))
from utils.qutils import parse_quirk_url, quirk_to_qasm, quirk_circuit_info, encode_quirk_url


def find_input_dir():
    search_roots = [Path.cwd(), Path.cwd() / "notebooks", Path.cwd().parent / "notebooks"]
    for root in search_roots:
        input_dir = root / "input"
        if (input_dir / "algorithms.json").is_file() and (input_dir / "popular_algorithms.json").is_file():
            return input_dir
    raise FileNotFoundError("No se encontró input/algorithms.json ni input/popular_algorithms.json")


def load_algorithms():
    path = find_input_dir() / "algorithms.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_popular_algorithms():
    path = find_input_dir() / "popular_algorithms.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


ALGORITHMS = load_algorithms()
POPULAR_ALGORITHMS = load_popular_algorithms()


def describe_algorithms(algorithms, title):
    print(f"Se recorrieron {len(algorithms)} items en {title}")
    md = f"## {title}\n\n| # | Algoritmo | Qubits | Descripción |\n|---|---|---|---|\n"
    for key, value in algorithms.items():
        info = quirk_circuit_info(value["url"])
        n_qubits = info["n_qubits"]
        algorithm_name = key.split(". ", 1)[1] if ". " in key else key
        md += f'| {key.split(".", 1)[0]} | **{algorithm_name}** | {n_qubits} | {value["desc"]} |\n'
    display(Markdown(md))


describe_algorithms(ALGORITHMS, "Algoritmos")
describe_algorithms(POPULAR_ALGORITHMS, "Popular algorithms")

Se recorrieron 15 items en Algoritmos

## Algoritmos

| # | Algoritmo | Qubits | Descripción |
|---|---|---|---|
| 1 | **Shor** | 4 | Algoritmo de factorización de Shor (4 qubits) |
| 2 | **Bernstein-Vazirani** | 4 | Algoritmo de Bernstein-Vazirani (4 qubits) |
| 3 | **Grover** | 2 | Algoritmo de búsqueda de Grover (2 qubits) |
| 4 | **Deutsch-Jozsa** | 4 | Algoritmo de Deutsch-Jozsa (4 qubits) |
| 5 | **Simon** | 6 | Algoritmo de Simon (6 qubits) |
| 6 | **TSP** | 3 | Circuito para problema del viajante (TSP, 3 qubits) |
| 7 | **Teleportation** | 5 | Protocolo de teleportación cuántica (5 qubits) |
| 8 | **Phase Estimation** | 4 | Estimación de fase cuántica (4 qubits + compuertas custom) |
| 9 | **QFT** | 3 | Transformada de Fourier Cuántica (3 qubits) |
| 10 | **QAOA** | 2 | Quantum Approximate Optimization Algorithm (2 qubits) |
| 11 | **Kickback** | 2 | Phase kickback (2 qubits) |
| 12 | **Full Adder** | 4 | Sumador completo (4 qubits) |
| 13 | **Multicontroled Gates** | 5 | Circuito de prueba con compuertas multicontroladas CCX, CCY, CCZ, CCCX, CCCY y CCCZ |
| 14 | **Shor_6q** | 6 | Algoritmo de factorización de Shor (6 qubits) |
| 15 | **Popurri_6q** | 6 | Algoritmo combinado para pruebas multicontroladas (6 qubits) |

Se recorrieron 38 items en Popular algorithms

## Popular algorithms

| # | Algoritmo | Qubits | Descripción |
|---|---|---|---|
| 1 | **adder_n4_vq** | 4 | Circuito adder_n4_vq (4 qubits) |
| 2 | **adder_n10_vq** | 10 | Circuito adder_n10_vq (10 qubits) |
| 3 | **adder_n13_vq** | 13 | Circuito adder_n13_vq (13 qubits) |
| 4 | **adder_n16_vq** | 16 | Circuito adder_n16_vq (16 qubits) |
| 5 | **bv_2_vq** | 2 | Circuito bv_2_vq (2 qubits) |
| 6 | **bv_3_vq** | 3 | Circuito bv_3_vq (3 qubits) |
| 7 | **bv_4_vq** | 4 | Circuito bv_4_vq (4 qubits) |
| 8 | **bv_5_vq** | 5 | Circuito bv_5_vq (5 qubits) |
| 9 | **bv_9_vq** | 9 | Circuito bv_9_vq (9 qubits) |
| 10 | **bv_14_vq** | 14 | Circuito bv_14_vq (14 qubits) |
| 11 | **dj_indep_4_mqt** | 4 | Circuito dj_indep_4_mqt (4 qubits) |
| 12 | **dj_indep_5_mqt** | 5 | Circuito dj_indep_5_mqt (5 qubits) |
| 13 | **dj_indep_7_mqt** | 7 | Circuito dj_indep_7_mqt (7 qubits) |
| 14 | **dj_indep_14_mqt** | 14 | Circuito dj_indep_14_mqt (14 qubits) |
| 15 | **grover-noancilla_3_mqt** | 3 | Circuito grover-noancilla_3_mqt (3 qubits) |
| 16 | **grover-noancilla_4_mqt** | 4 | Circuito grover-noancilla_4_mqt (4 qubits) |
| 17 | **grover-v-chain_3_mqt** | 3 | Circuito grover-v-chain_3_mqt (3 qubits) |
| 18 | **grover-v-chain_4_mqt** | 4 | Circuito grover-v-chain_4_mqt (4 qubits) |
| 19 | **grover_3_vq** | 3 | Circuito grover_3_vq (3 qubits) |
| 20 | **grover_7_vq** | 7 | Circuito grover_7_vq (7 qubits) |
| 21 | **grover_9_vq** | 9 | Circuito grover_9_vq (9 qubits) |
| 22 | **kickback_7_vq** | 7 | Circuito kickback_7_vq (7 qubits) |
| 23 | **pe_2_vq** | 3 | Circuito pe_2_vq (3 qubits) |
| 24 | **pe_3_mqt** | 3 | Circuito pe_3_mqt (3 qubits) |
| 25 | **pe_4_mqt** | 4 | Circuito pe_4_mqt (4 qubits) |
| 26 | **pe_5_mqt** | 5 | Circuito pe_5_mqt (5 qubits) |
| 27 | **pe_6_mqt** | 6 | Circuito pe_6_mqt (6 qubits) |
| 28 | **pe_7_mqt** | 7 | Circuito pe_7_mqt (7 qubits) |
| 29 | **qft_2_mqt** | 2 | Circuito qft_2_mqt (2 qubits) |
| 30 | **qft_3_mqt** | 3 | Circuito qft_3_mqt (3 qubits) |
| 31 | **qft_4_mqt** | 4 | Circuito qft_4_mqt (4 qubits) |
| 32 | **qft_6_mqt** | 6 | Circuito qft_6_mqt (6 qubits) |
| 33 | **qft_7_vq** | 7 | Circuito qft_7_vq (7 qubits) |
| 34 | **shor_mod15_mqt** | 5 | Circuito shor_mod15_mqt (5 qubits) |
| 35 | **shor_mod21_mqt** | 8 | Circuito shor_mod21_mqt (8 qubits) |
| 36 | **simon_vq** | 6 | Circuito simon_vq (6 qubits) |
| 37 | **tsp_indep_4_mqt** | 4 | Circuito tsp_indep_4_mqt (4 qubits) |
| 38 | **tsp_indep_5_mqt** | 5 | Circuito tsp_indep_5_mqt (5 qubits) |

### Captura de screenshots de circuitos originales desde Quirk (navegador)

Genera archivos en el path: /circuits_quirk

In [3]:
import base64
import subprocess
import sys

try:
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC
except ImportError:
    print("Instalando selenium...")
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'selenium'])
    from selenium import webdriver
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC

from pathlib import Path
import time
import re

quirk_original_dir = Path.cwd() / 'circuits_quirk'
quirk_original_dir.mkdir(exist_ok=True)

def natural_sort_key(value):
    text = str(value).strip()
    match = re.search(r'^(\d+)', text)
    if match:
        num = int(match.group(1))
        return (num, text)
    else:
        return (float('inf'), text)

def capture_quirk_circuit(url, output_path):
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--window-size=1920,1080')

    driver = None
    try:
        driver = webdriver.Chrome(options=options)
        driver.get(url)

        wait = WebDriverWait(driver, 10)
        wait.until(EC.presence_of_element_located((By.TAG_NAME, 'canvas')))
        time.sleep(2)

        page_size = driver.execute_script("""
            const root = document.documentElement;
            const body = document.body;
            return {
                width: Math.max(root.scrollWidth, body.scrollWidth, root.clientWidth),
                height: Math.max(root.scrollHeight, body.scrollHeight, root.clientHeight)
            };
        """)
        screenshot = driver.execute_cdp_cmd('Page.captureScreenshot', {
            'format': 'png',
            'fromSurface': True,
            'captureBeyondViewport': True,
            'clip': {
                'x': 0,
                'y': 0,
                'width': page_size['width'],
                'height': page_size['height'],
                'scale': 1,
            },
        })
        Path(output_path).write_bytes(base64.b64decode(screenshot['data']))
        return True
    except Exception as exc:
        print(f"  Error capturando {url}: {exc}")
        return False
    finally:
        if driver:
            driver.quit()

print('Captura de screenshots de circuitos originales desde Quirk\n')

ALGORITHMS = load_algorithms()
POPULAR_ALGORITHMS = load_popular_algorithms()
captured = 0
total_circuits = len(ALGORITHMS) + len(POPULAR_ALGORITHMS)
algorithm_collections = [
    (ALGORITHMS, ''),
    (POPULAR_ALGORITHMS, 'popular_'),
]

for algorithms, filename_prefix in algorithm_collections:
    for name, data in sorted(algorithms.items(), key=lambda item: natural_sort_key(item[0])):
        url = data['url']
        safe_name = name.replace('.', '_').replace(' ', '_')
        output_path = quirk_original_dir / f'{filename_prefix}{safe_name}.png'

        print(f'Capturando: {name}...', end=' ')
        if capture_quirk_circuit(url, output_path):
            print(f'✅ Guardado en {output_path.name}')
            captured += 1
        else:
            print('❌ Error')

print(f'\n✓ Captura completada: {captured}/{total_circuits} screenshots guardados')
print(f'Archivos disponibles en: /{quirk_original_dir.name}')

Captura de screenshots de circuitos originales desde Quirk

Capturando: 1. Shor... ✅ Guardado en 1__Shor.png
Capturando: 2. Bernstein-Vazirani... ✅ Guardado en 2__Bernstein-Vazirani.png
Capturando: 3. Grover... ✅ Guardado en 3__Grover.png
Capturando: 4. Deutsch-Jozsa... ✅ Guardado en 4__Deutsch-Jozsa.png
Capturando: 5. Simon... ✅ Guardado en 5__Simon.png
Capturando: 6. TSP... ✅ Guardado en 6__TSP.png
Capturando: 7. Teleportation... ✅ Guardado en 7__Teleportation.png
Capturando: 8. Phase Estimation... ✅ Guardado en 8__Phase_Estimation.png
Capturando: 9. QFT... ✅ Guardado en 9__QFT.png
Capturando: 10. QAOA... ✅ Guardado en 10__QAOA.png
Capturando: 11. Kickback... ✅ Guardado en 11__Kickback.png
Capturando: 12. Full Adder... ✅ Guardado en 12__Full_Adder.png
Capturando: 13. Multicontroled Gates... ✅ Guardado en 13__Multicontroled_Gates.png
Capturando: 14. Shor_6q... ✅ Guardado en 14__Shor_6q.png
Capturando: 15. Popurri_6q... ✅ Guardado en 15__Popurri_6q.png
Capturando: 1. adder_n4_vq... ✅ Guardado en popular_1__adder_n4_vq.png
Capturando: 2. adder_n10_vq... ✅ Guardado en popular_2__adder_n10_vq.png
Capturando: 3. adder_n13_vq... ✅ Guardado en popular_3__adder_n13_vq.png
Capturando: 4. adder_n16_vq... ✅ Guardado en popular_4__adder_n16_vq.png
Capturando: 5. bv_2_vq... ✅ Guardado en popular_5__bv_2_vq.png
Capturando: 6. bv_3_vq... ✅ Guardado en popular_6__bv_3_vq.png
Capturando: 7. bv_4_vq... ✅ Guardado en popular_7__bv_4_vq.png
Capturando: 8. bv_5_vq... ✅ Guardado en popular_8__bv_5_vq.png
Capturando: 9. bv_9_vq... ✅ Guardado en popular_9__bv_9_vq.png
Capturando: 10. bv_14_vq... ✅ Guardado en popular_10__bv_14_vq.png
Capturando: 11. dj_indep_4_mqt... ✅ Guardado en popular_11__dj_indep_4_mqt.png
Capturando: 12. dj_indep_5_mqt... ✅ Guardado en popular_12__dj_indep_5_mqt.png
Capturando: 13. dj_indep_7_mqt... ✅ Guardado en popular_13__dj_indep_7_mqt.png
Capturando: 14. dj_indep_14_mqt... ✅ Guardado en popular_14__dj_indep_14_mqt.png
Capturando: 15. grover-noancilla_3_mqt... ✅ Guardado en popular_15__grover-noancilla_3_mqt.png
Capturando: 16. grover-noancilla_4_mqt... ✅ Guardado en popular_16__grover-noancilla_4_mqt.png
Capturando: 17. grover-v-chain_3_mqt... ✅ Guardado en popular_17__grover-v-chain_3_mqt.png
Capturando: 18. grover-v-chain_4_mqt... ✅ Guardado en popular_18__grover-v-chain_4_mqt.png
Capturando: 19. grover_3_vq... ✅ Guardado en popular_19__grover_3_vq.png
Capturando: 20. grover_7_vq... ✅ Guardado en popular_20__grover_7_vq.png
Capturando: 21. grover_9_vq... ✅ Guardado en popular_21__grover_9_vq.png
Capturando: 22. kickback_7_vq... ✅ Guardado en popular_22__kickback_7_vq.png
Capturando: 23. pe_2_vq... ✅ Guardado en popular_23__pe_2_vq.png
Capturando: 24. pe_3_mqt... ✅ Guardado en popular_24__pe_3_mqt.png
Capturando: 25. pe_4_mqt... ✅ Guardado en popular_25__pe_4_mqt.png
Capturando: 26. pe_5_mqt... ✅ Guardado en popular_26__pe_5_mqt.png
Capturando: 27. pe_6_mqt... ✅ Guardado en popular_27__pe_6_mqt.png
Capturando: 28. pe_7_mqt... ✅ Guardado en popular_28__pe_7_mqt.png
Capturando: 29. qft_2_mqt... ✅ Guardado en popular_29__qft_2_mqt.png
Capturando: 30. qft_3_mqt... ✅ Guardado en popular_30__qft_3_mqt.png
Capturando: 31. qft_4_mqt... ✅ Guardado en popular_31__qft_4_mqt.png
Capturando: 32. qft_6_mqt... ✅ Guardado en popular_32__qft_6_mqt.png
Capturando: 33. qft_7_vq... ✅ Guardado en popular_33__qft_7_vq.png
Capturando: 34. shor_mod15_mqt... ✅ Guardado en popular_34__shor_mod15_mqt.png
Capturando: 35. shor_mod21_mqt... ✅ Guardado en popular_35__shor_mod21_mqt.png
Capturando: 36. simon_vq... ✅ Guardado en popular_36__simon_vq.png
Capturando: 37. tsp_indep_4_mqt... ✅ Guardado en popular_37__tsp_indep_4_mqt.png
Capturando: 38. tsp_indep_5_mqt... ✅ Guardado en popular_38__tsp_indep_5_mqt.png

✓ Captura completada: 53/53 screenshots guardados
Archivos disponibles en: /circuits_quirk

2. Traducción de algoritmos (algorithms.json) desde Quirk --> OpenQASM 3.0

### Generación de circuitos en formato textual (.txt) en OpenQASM3

En path: /algorithms_qasm

In [4]:
import os
import pandas as pd
from pathlib import Path

# Creamos un directorio para almacenar los archivos QASM generados
output_dir = Path.cwd() / "algorithms_qasm"
output_dir.mkdir(exist_ok=True)


def generate_qasm_table_and_files():
    rows = []
    generated_paths = []
    algorithm_collections = [
        ("Algoritmos", ALGORITHMS, ""),
        ("Popular", POPULAR_ALGORITHMS, "popular_"),
    ]

    for collection_name, algorithms, filename_prefix in algorithm_collections:
        for name, data in algorithms.items():
            url = data["url"]
            info = quirk_circuit_info(url)
            qasm_code = quirk_to_qasm(url, data.get("offset", 0))

            safe_name = name.replace(".", "_").replace(" ", "_")
            file_path = output_dir / f"{filename_prefix}{safe_name}.txt"
            file_path.write_text(qasm_code, encoding="utf-8")
            generated_paths.append(file_path.resolve())

            rows.append({
                "Colección": collection_name,
                "Algoritmo": name.split(". ", 1)[1] if ". " in name else name,
                "Qubits": info["n_qubits"],
                "Columnas": info["n_cols"],
                "Descripcion": data.get("desc", ""),
                "Archivo": str(file_path.name),
                "Líneas": len(qasm_code.splitlines())
            })

    total_archivos = len(generated_paths)
    print(f"Todos los archivos generados en el path: /{output_dir.name} ({total_archivos} archivos)")
    for generated_path in generated_paths:
        print(f"- {generated_path.name}")

    df = pd.DataFrame(rows)
    return df


generate_qasm_table_and_files()

Todos los archivos generados en el path: /algorithms_qasm (53 archivos)
- 1__Shor.txt
- 2__Bernstein-Vazirani.txt
- 3__Grover.txt
- 4__Deutsch-Jozsa.txt
- 5__Simon.txt
- 6__TSP.txt
- 7__Teleportation.txt
- 8__Phase_Estimation.txt
- 9__QFT.txt
- 10__QAOA.txt
- 11__Kickback.txt
- 12__Full_Adder.txt
- 13__Multicontroled_Gates.txt
- 14__Shor_6q.txt
- 15__Popurri_6q.txt
- popular_1__adder_n4_vq.txt
- popular_2__adder_n10_vq.txt
- popular_3__adder_n13_vq.txt
- popular_4__adder_n16_vq.txt
- popular_5__bv_2_vq.txt
- popular_6__bv_3_vq.txt
- popular_7__bv_4_vq.txt
- popular_8__bv_5_vq.txt
- popular_9__bv_9_vq.txt
- popular_10__bv_14_vq.txt
- popular_11__dj_indep_4_mqt.txt
- popular_12__dj_indep_5_mqt.txt
- popular_13__dj_indep_7_mqt.txt
- popular_14__dj_indep_14_mqt.txt
- popular_15__grover-noancilla_3_mqt.txt
- popular_16__grover-noancilla_4_mqt.txt
- popular_17__grover-v-chain_3_mqt.txt
- popular_18__grover-v-chain_4_mqt.txt
- popular_19__grover_3_vq.txt
- popular_20__grover_7_vq.txt
- popular_21__grover_9_vq.txt
- popular_22__kickback_7_vq.txt
- popular_23__pe_2_vq.txt
- popular_24__pe_3_mqt.txt
- popular_25__pe_4_mqt.txt
- popular_26__pe_5_mqt.txt
- popular_27__pe_6_mqt.txt
- popular_28__pe_7_mqt.txt
- popular_29__qft_2_mqt.txt
- popular_30__qft_3_mqt.txt
- popular_31__qft_4_mqt.txt
- popular_32__qft_6_mqt.txt
- popular_33__qft_7_vq.txt
- popular_34__shor_mod15_mqt.txt
- popular_35__shor_mod21_mqt.txt
- popular_36__simon_vq.txt
- popular_37__tsp_indep_4_mqt.txt
- popular_38__tsp_indep_5_mqt.txt

,Colección,Algoritmo,Qubits,Columnas,Descripcion,Archivo,Líneas
0,Algoritmos,Shor,4,13,Algoritmo de factorización de Shor (4 qubits),1__Shor.txt,26
1,Algoritmos,Bernstein-Vazirani,4,8,Algoritmo de Bernstein-Vazirani (4 qubits),2__Bernstein-Vazirani.txt,18
2,Algoritmos,Grover,2,8,Algoritmo de búsqueda de Grover (2 qubits),3__Grover.txt,13
3,Algoritmos,Deutsch-Jozsa,4,9,Algoritmo de Deutsch-Jozsa (4 qubits),4__Deutsch-Jozsa.txt,22
4,Algoritmos,Simon,6,8,Algoritmo de Simon (6 qubits),5__Simon.txt,18
5,Algoritmos,TSP,3,6,"Circuito para problema del viajante (TSP, 3 qu...",6__TSP.txt,13
6,Algoritmos,Teleportation,5,8,Protocolo de teleportación cuántica (5 qubits),7__Teleportation.txt,13
7,Algoritmos,Phase Estimation,4,17,Estimación de fase cuántica (4 qubits + compue...,8__Phase_Estimation.txt,26
8,Algoritmos,QFT,3,8,Transformada de Fourier Cuántica (3 qubits),9__QFT.txt,15
9,Algoritmos,QAOA,2,12,Quantum Approximate Optimization Algorithm (2 ...,10__QAOA.txt,8
10,Algoritmos,Kickback,2,6,Phase kickback (2 qubits),11__Kickback.txt,12
11,Algoritmos,Full Adder,4,10,Sumador completo (4 qubits),12__Full_Adder.txt,16
12,Algoritmos,Multicontroled Gates,5,8,Circuito de prueba con compuertas multicontrol...,13__Multicontroled_Gates.txt,20
13,Algoritmos,Shor_6q,6,16,Algoritmo de factorización de Shor (6 qubits),14__Shor_6q.txt,35
14,Algoritmos,Popurri_6q,6,25,Algoritmo combinado para pruebas multicontrola...,15__Popurri_6q.txt,46
15,Popular,adder_n4_vq,4,8,Circuito adder_n4_vq (4 qubits),popular_1__adder_n4_vq.txt,12
16,Popular,adder_n10_vq,10,12,Circuito adder_n10_vq (10 qubits),popular_2__adder_n10_vq.txt,16
17,Popular,adder_n13_vq,13,29,Circuito adder_n13_vq (13 qubits),popular_3__adder_n13_vq.txt,33
18,Popular,adder_n16_vq,16,36,Circuito adder_n16_vq (16 qubits),popular_4__adder_n16_vq.txt,40
19,Popular,bv_2_vq,2,6,Circuito bv_2_vq (2 qubits),popular_5__bv_2_vq.txt,10
20,Popular,bv_3_vq,3,12,Circuito bv_3_vq (3 qubits),popular_6__bv_3_vq.txt,16
21,Popular,bv_4_vq,4,16,Circuito bv_4_vq (4 qubits),popular_7__bv_4_vq.txt,20
22,Popular,bv_5_vq,5,20,Circuito bv_5_vq (5 qubits),popular_8__bv_5_vq.txt,24
23,Popular,bv_9_vq,9,36,Circuito bv_9_vq (9 qubits),popular_9__bv_9_vq.txt,40
24,Popular,bv_14_vq,14,55,Circuito bv_14_vq (14 qubits),popular_10__bv_14_vq.txt,59
25,Popular,dj_indep_4_mqt,4,13,Circuito dj_indep_4_mqt (4 qubits),popular_11__dj_indep_4_mqt.txt,17
26,Popular,dj_indep_5_mqt,5,17,Circuito dj_indep_5_mqt (5 qubits),popular_12__dj_indep_5_mqt.txt,21
27,Popular,dj_indep_7_mqt,7,25,Circuito dj_indep_7_mqt (7 qubits),popular_13__dj_indep_7_mqt.txt,29
28,Popular,dj_indep_14_mqt,14,53,Circuito dj_indep_14_mqt (14 qubits),popular_14__dj_indep_14_mqt.txt,57
29,Popular,grover-noancilla_3_mqt,3,16,Circuito grover-noancilla_3_mqt (3 qubits),popular_15__grover-noancilla_3_mqt.txt,20
30,Popular,grover-noancilla_4_mqt,4,48,Circuito grover-noancilla_4_mqt (4 qubits),popular_16__grover-noancilla_4_mqt.txt,52
31,Popular,grover-v-chain_3_mqt,3,16,Circuito grover-v-chain_3_mqt (3 qubits),popular_17__grover-v-chain_3_mqt.txt,20
32,Popular,grover-v-chain_4_mqt,4,48,Circuito grover-v-chain_4_mqt (4 qubits),popular_18__grover-v-chain_4_mqt.txt,52
33,Popular,grover_3_vq,3,19,Circuito grover_3_vq (3 qubits),popular_19__grover_3_vq.txt,23
34,Popular,grover_7_vq,7,39,Circuito grover_7_vq (7 qubits),popular_20__grover_7_vq.txt,43
35,Popular,grover_9_vq,9,50,Circuito grover_9_vq (9 qubits),popular_21__grover_9_vq.txt,54
36,Popular,kickback_7_vq,7,10,Circuito kickback_7_vq (7 qubits),popular_22__kickback_7_vq.txt,15
37,Popular,pe_2_vq,3,10,Circuito pe_2_vq (3 qubits),popular_23__pe_2_vq.txt,15
38,Popular,pe_3_mqt,3,10,Circuito pe_3_mqt (3 qubits),popular_24__pe_3_mqt.txt,14
39,Popular,pe_4_mqt,4,15,Circuito pe_4_mqt (4 qubits),popular_25__pe_4_mqt.txt,19
40,Popular,pe_5_mqt,5,25,Circuito pe_5_mqt (5 qubits),popular_26__pe_5_mqt.txt,30
41,Popular,pe_6_mqt,6,32,Circuito pe_6_mqt (6 qubits),popular_27__pe_6_mqt.txt,37
42,Popular,pe_7_mqt,7,41,Circuito pe_7_mqt (7 qubits),popular_28__pe_7_mqt.txt,46
43,Popular,qft_2_mqt,2,6,Circuito qft_2_mqt (2 qubits),popular_29__qft_2_mqt.txt,10
44,Popular,qft_3_mqt,3,10,Circuito qft_3_mqt (3 qubits),popular_30__qft_3_mqt.txt,14
45,Popular,qft_4_mqt,4,16,Circuito qft_4_mqt (4 qubits),popular_31__qft_4_mqt.txt,21
46,Popular,qft_6_mqt,6,30,Circuito qft_6_mqt (6 qubits),popular_32__qft_6_mqt.txt,35
47,Popular,qft_7_vq,7,35,Circuito qft_7_vq (7 qubits),popular_33__qft_7_vq.txt,40
48,Popular,shor_mod15_mqt,5,20,Circuito shor_mod15_mqt (5 qubits),popular_34__shor_mod15_mqt.txt,24
49,Popular,shor_mod21_mqt,8,19,Circuito shor_mod21_mqt (8 qubits),popular_35__shor_mod21_mqt.txt,23
50,Popular,simon_vq,6,16,Circuito simon_vq (6 qubits),popular_36__simon_vq.txt,20
51,Popular,tsp_indep_4_mqt,4,43,Circuito tsp_indep_4_mqt (4 qubits),popular_37__tsp_indep_4_mqt.txt,48
52,Popular,tsp_indep_5_mqt,5,29,Circuito tsp_indep_5_mqt (5 qubits),popular_38__tsp_indep_5_mqt.txt,33

### Generación de imágenes de circuitos traducidos OpenQASM3

Genera archivos en el path: /circuits_qasm

In [6]:
from pathlib import Path
import re
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit
from qiskit.qasm3 import loads as qasm3_loads


circuits_dir = Path.cwd() / 'circuits_qasm'
circuits_dir.mkdir(exist_ok=True)


def natural_sort_key(value):
    parts = re.split(r'[_\s.-]+', str(value))
    return [(0, int(p)) if p.isdigit() else (1, p.lower()) for p in parts if p]


def load_qasm_circuit(qasm_text: str):
    text = (qasm_text or '').strip()
    if not text:
        raise ValueError('El contenido QASM está vacío')

    upper = text.upper()
    if upper.startswith('OPENQASM 3.0'):
        return qasm3_loads(text)
    if upper.startswith('OPENQASM 2.0'):
        return QuantumCircuit.from_qasm_str(text)

    try:
        return qasm3_loads(text)
    except Exception:
        return QuantumCircuit.from_qasm_str(text)


def render_qasm_circuits():
    qasm_dir = Path.cwd() / 'algorithms_qasm'
    circuits_dir = Path.cwd() / 'circuits_qasm'
    circuits_dir.mkdir(exist_ok=True)

    if not qasm_dir.exists():
        raise FileNotFoundError(f'No existe la carpeta de QASM: {qasm_dir}')

    files = sorted(qasm_dir.glob('*.txt'), key=lambda p: natural_sort_key(p.stem))
    if not files:
        raise FileNotFoundError(f'No hay archivos .txt en {qasm_dir}')

    rendered = 0
    failed = 0
    for txt_path in files:
        qasm_text = txt_path.read_text(encoding='utf-8')

        try:
            circuit = load_qasm_circuit(qasm_text)
        except Exception as exc:
            print(f'No se pudo cargar {txt_path.name} ({type(exc).__name__}): {exc!r}')
            failed += 1
            continue

        png_path = circuits_dir / f'{txt_path.stem}.png'
        figure = None
        try:
            figure = circuit.draw(output='mpl', filename=str(png_path), style='bw')
            print(f'Generado: {png_path.name}')
            rendered += 1
        except Exception as exc:
            print(f'No se pudo dibujar {txt_path.name} ({type(exc).__name__}): {exc!r}')
            failed += 1
        finally:
            if figure is not None:
                plt.close(figure)

    print(f'Resumen: {rendered}/{len(files)} imágenes generadas; {failed} archivos con error.')


print(f'Generación de imágenes de circuitos traducidos a OpenQASM 3.0 ( {circuits_dir.resolve()} )\n')
render_qasm_circuits()

Matplotlib is building the font cache; this may take a moment.

Generación de imágenes de circuitos traducidos a OpenQASM 3.0 ( C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\circuits_qasm )

Generado: 1__Shor.png
Generado: 2__Bernstein-Vazirani.png
Generado: 3__Grover.png
Generado: 4__Deutsch-Jozsa.png
Generado: 5__Simon.png
Generado: 6__TSP.png
Generado: 7__Teleportation.png
Generado: 8__Phase_Estimation.png
Generado: 9__QFT.png
Generado: 10__QAOA.png
Generado: 11__Kickback.png
Generado: 12__Full_Adder.png
Generado: 13__Multicontroled_Gates.png
Generado: 14__Shor_6q.png
Generado: 15__Popurri_6q.png
Generado: popular_1__adder_n4_vq.png
Generado: popular_2__adder_n10_vq.png
Generado: popular_3__adder_n13_vq.png
Generado: popular_4__adder_n16_vq.png
Generado: popular_5__bv_2_vq.png
Generado: popular_6__bv_3_vq.png
Generado: popular_7__bv_4_vq.png
Generado: popular_8__bv_5_vq.png
Generado: popular_9__bv_9_vq.png
Generado: popular_10__bv_14_vq.png
Generado: popular_11__dj_indep_4_mqt.png
Generado: popular_12__dj_indep_5_mqt.png
Generado: popular_13__dj_indep_7_mqt.png
Generado: popular_14__dj_indep_14_mqt.png
Generado: popular_15__grover-noancilla_3_mqt.png
Generado: popular_16__grover-noancilla_4_mqt.png
Generado: popular_17__grover-v-chain_3_mqt.png
Generado: popular_18__grover-v-chain_4_mqt.png
Generado: popular_19__grover_3_vq.png
Generado: popular_20__grover_7_vq.png
Generado: popular_21__grover_9_vq.png
Generado: popular_22__kickback_7_vq.png
Generado: popular_23__pe_2_vq.png
Generado: popular_24__pe_3_mqt.png
Generado: popular_25__pe_4_mqt.png
Generado: popular_26__pe_5_mqt.png
Generado: popular_27__pe_6_mqt.png
Generado: popular_28__pe_7_mqt.png
Generado: popular_29__qft_2_mqt.png
Generado: popular_30__qft_3_mqt.png
Generado: popular_31__qft_4_mqt.png
Generado: popular_32__qft_6_mqt.png
Generado: popular_33__qft_7_vq.png
Generado: popular_34__shor_mod15_mqt.png
Generado: popular_35__shor_mod21_mqt.png
Generado: popular_36__simon_vq.png
Generado: popular_37__tsp_indep_4_mqt.png
Generado: popular_38__tsp_indep_5_mqt.png
Resumen: 53/53 imágenes generadas; 0 archivos con error.

### Generamos una carpeta de comparación para agilizar la verificación de equivalencia visual

Establece la generación de imágenes generadas (circuitos quirk y qasm )

Directorio de salida: notebooks/compare

In [7]:
from pathlib import Path
import re

project_root = Path.cwd()
compare_dir = project_root / 'compare'
compare_dir.mkdir(exist_ok=True)

qasm_dir = project_root / 'circuits_qasm'
quirk_dir = project_root / 'circuits_quirk'

if not qasm_dir.exists():
    raise FileNotFoundError(f'No existe la carpeta de circuitos OpenQASM: {qasm_dir}')
if not quirk_dir.exists():
    raise FileNotFoundError(f'No existe la carpeta de circuitos Quirk: {quirk_dir}')


def natural_sort_key(value):
    parts = re.split(r'[_\s.-]+', str(value))
    return [(0, int(part)) if part.isdigit() else (1, part.lower()) for part in parts if part]


qasm_pngs = {path.stem: path for path in qasm_dir.glob('*.png')}
quirk_pngs = {path.stem: path for path in quirk_dir.glob('*.png')}
matching_names = sorted(set(qasm_pngs) & set(quirk_pngs), key=natural_sort_key)

index_lines = ['# Comparación de circuitos', '']

for stem in matching_names:
    qasm_path = qasm_pngs[stem]
    quirk_path = quirk_pngs[stem]
    title = stem.replace('_', ' ')
    md_path = compare_dir / f'{stem}.md'
    md_path.write_text(
        '\n'.join([
            f'# Comparación: {title}',
            '',
            '<table>',
            '<tr><th align="center">Circuito Original (Quirk)</th><th align="center">Circuito traducido (OpenQASM 3.0)</th></tr>',
            '<tr>',
            '<td align="center"><a href="../circuits_quirk/' + quirk_path.name + '" title="Abrir imagen original"><img src="../circuits_quirk/' + quirk_path.name + '" alt="' + quirk_path.name + '" width="100%" /></a></td>',
            '<td align="center"><a href="../circuits_qasm/' + qasm_path.name + '" title="Abrir imagen original"><img src="../circuits_qasm/' + qasm_path.name + '" alt="' + qasm_path.name + '" width="100%" /></a></td>',
            '</tr>',
            '</table>',
            '',
        ]),
        encoding='utf-8'
    )

    index_lines.append(f'- [{title}]({stem}.md)')
    print(f'Generado info comparativa --> {md_path.name}')

index_path = compare_dir / 'README.md'
index_path.write_text('\n'.join(index_lines) + '\n', encoding='utf-8')

print(f'\nCarpeta de comparación creada en: {compare_dir.resolve()}')
print(f'Se generaron {len(matching_names)} comparativas para archivos presentes en ambas carpetas.')
print(f'Índice disponible en: {index_path.resolve()}')

Generado info comparativa --> 1__Shor.md
Generado info comparativa --> 2__Bernstein-Vazirani.md
Generado info comparativa --> 3__Grover.md
Generado info comparativa --> 4__Deutsch-Jozsa.md
Generado info comparativa --> 5__Simon.md
Generado info comparativa --> 6__TSP.md
Generado info comparativa --> 7__Teleportation.md
Generado info comparativa --> 8__Phase_Estimation.md
Generado info comparativa --> 9__QFT.md
Generado info comparativa --> 10__QAOA.md
Generado info comparativa --> 11__Kickback.md
Generado info comparativa --> 12__Full_Adder.md
Generado info comparativa --> 13__Multicontroled_Gates.md
Generado info comparativa --> 14__Shor_6q.md
Generado info comparativa --> 15__Popurri_6q.md
Generado info comparativa --> popular_1__adder_n4_vq.md
Generado info comparativa --> popular_2__adder_n10_vq.md
Generado info comparativa --> popular_3__adder_n13_vq.md
Generado info comparativa --> popular_4__adder_n16_vq.md
Generado info comparativa --> popular_5__bv_2_vq.md
Generado info comparativa --> popular_6__bv_3_vq.md
Generado info comparativa --> popular_7__bv_4_vq.md
Generado info comparativa --> popular_8__bv_5_vq.md
Generado info comparativa --> popular_9__bv_9_vq.md
Generado info comparativa --> popular_10__bv_14_vq.md
Generado info comparativa --> popular_11__dj_indep_4_mqt.md
Generado info comparativa --> popular_12__dj_indep_5_mqt.md
Generado info comparativa --> popular_13__dj_indep_7_mqt.md
Generado info comparativa --> popular_14__dj_indep_14_mqt.md
Generado info comparativa --> popular_15__grover-noancilla_3_mqt.md
Generado info comparativa --> popular_16__grover-noancilla_4_mqt.md
Generado info comparativa --> popular_17__grover-v-chain_3_mqt.md
Generado info comparativa --> popular_18__grover-v-chain_4_mqt.md
Generado info comparativa --> popular_19__grover_3_vq.md
Generado info comparativa --> popular_20__grover_7_vq.md
Generado info comparativa --> popular_21__grover_9_vq.md
Generado info comparativa --> popular_22__kickback_7_vq.md
Generado info comparativa --> popular_23__pe_2_vq.md
Generado info comparativa --> popular_24__pe_3_mqt.md
Generado info comparativa --> popular_25__pe_4_mqt.md
Generado info comparativa --> popular_26__pe_5_mqt.md
Generado info comparativa --> popular_27__pe_6_mqt.md
Generado info comparativa --> popular_28__pe_7_mqt.md
Generado info comparativa --> popular_29__qft_2_mqt.md
Generado info comparativa --> popular_30__qft_3_mqt.md
Generado info comparativa --> popular_31__qft_4_mqt.md
Generado info comparativa --> popular_32__qft_6_mqt.md
Generado info comparativa --> popular_33__qft_7_vq.md
Generado info comparativa --> popular_34__shor_mod15_mqt.md
Generado info comparativa --> popular_35__shor_mod21_mqt.md
Generado info comparativa --> popular_36__simon_vq.md
Generado info comparativa --> popular_37__tsp_indep_4_mqt.md
Generado info comparativa --> popular_38__tsp_indep_5_mqt.md

Carpeta de comparación creada en: C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\compare
Se generaron 53 comparativas para archivos presentes en ambas carpetas.
Índice disponible en: C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\compare\README.md

## Generación de grafos ZX a partir del json (url) Quirk

Obtenemos los grafos zx base sin pasar por OpenQASM.

In [ ]:
import json
import re
import sys
from pathlib import Path

project_root = next(
    (candidate for candidate in (Path.cwd(), Path.cwd().parent) if (candidate / 'utils' / 'qutils.py').is_file()),
    None,
)
if project_root is None:
    raise FileNotFoundError('No se encontró utils/qutils.py desde el directorio del notebook')
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.qutils import quirk_to_zx_graph

algorithms_dir = project_root / 'notebooks' / 'input'
if not (algorithms_dir / 'algorithms.json').is_file() or not (algorithms_dir / 'popular_algorithms.json').is_file():
    raise FileNotFoundError('No se encontraron algorithms.json y popular_algorithms.json dentro de notebooks/input')

algorithm_collections = [
    (json.loads((algorithms_dir / 'algorithms.json').read_text(encoding='utf-8')), ''),
    (json.loads((algorithms_dir / 'popular_algorithms.json').read_text(encoding='utf-8')), 'popular_'),
]
output_dir = project_root / 'notebooks' / 'ZXCalculus' / 'algorithms_base'
quirk_time = 0.5

graph_files = {}
for collection, filename_prefix in algorithm_collections:
    for name, data in collection.items():
        graph = quirk_to_zx_graph(data['url'], data.get('offset', 0), time=quirk_time)
        graph_json = graph.to_json()
        json.loads(graph_json)
        safe_name = re.sub(r'[^A-Za-z0-9_-]+', '_', name).strip('_')
        filename = f'{filename_prefix}{safe_name}.json'
        if filename in graph_files:
            raise ValueError(f'Nombre de archivo duplicado: {filename}')
        graph_files[filename] = graph_json

expected_graphs = sum(len(collection) for collection, _ in algorithm_collections)
if len(graph_files) != expected_graphs:
    raise RuntimeError(f'Se esperaban {expected_graphs} grafos, se generaron {len(graph_files)}')

output_dir.mkdir(parents=True, exist_ok=True)
for filename, graph_json in graph_files.items():
    (output_dir / filename).write_text(graph_json, encoding='utf-8')

print(f'Grafo ZX generado para {len(graph_files)} algoritmos.')
print(f'Snapshot temporal de Quirk: {quirk_time} (aplica a gates dependientes del tiempo como Rxft).')
print(f'Archivos guardados en: {output_dir.resolve()}')

Grafo ZX generado para 53 algoritmos.
Snapshot temporal de Quirk: 0.5 (aplica a gates dependientes del tiempo como Rxft).
Archivos guardados en: C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\ZXCalculus\algorithms_base

## Generación de grafos ZX a partir del código OpenQasm generado a partir de nuestra migración

Directorio asociado: /algorithms_qasm

In [ ]:
import importlib
import json
import sys
from pathlib import Path

project_root = next(
    (candidate for candidate in (Path.cwd(), Path.cwd().parent) if (candidate / 'utils' / 'qutils.py').is_file()),
    None,
)
if project_root is None:
    raise FileNotFoundError('No se encontró utils/qutils.py desde el directorio del notebook')
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils import qutils
importlib.reload(qutils)
qasm_to_zx_graph = qutils.qasm_to_zx_graph

qasm_dir = project_root / 'notebooks' / 'algorithms_qasm'
output_dir = project_root / 'notebooks' / 'ZXCalculus' / 'algorithms_qasm'
qasm_files = sorted(qasm_dir.glob('*.txt'))
if not qasm_files:
    raise FileNotFoundError(f'No hay archivos .txt en {qasm_dir}')

graph_files = {}
for qasm_path in qasm_files:
    qasm_code = qasm_path.read_text(encoding='utf-8')
    graph = qasm_to_zx_graph(qasm_code)
    graph_json = graph.to_json()
    json.loads(graph_json)
    graph_files[f'{qasm_path.stem}.json'] = graph_json

if len(graph_files) != len(qasm_files):
    raise RuntimeError(f'Se esperaban {len(qasm_files)} grafos, se generaron {len(graph_files)}')

output_dir.mkdir(parents=True, exist_ok=True)
for filename, graph_json in graph_files.items():
    (output_dir / filename).write_text(graph_json, encoding='utf-8')

print(f'Grafos ZX generados: {len(graph_files)}.')
print(f'Circuitos OpenQASM leídos desde: {qasm_dir.resolve()}')
print(f'Grafos guardados en: {output_dir.resolve()}')

Grafos ZX generados: 53.
Circuitos OpenQASM leídos desde: C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\algorithms_qasm
Grafos guardados en: C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\ZXCalculus\algorithms_qasm

# Comparación entre grafos ZX

Establecemos por cada algoritmo si la comparación de equivalencia es correcta, a fin de verificar la migración hacia OpenQASM.

In [ ]:
import re
from pathlib import Path

import pandas as pd
import pyzx as zx
from IPython.display import display

zx_candidates = [
    Path.cwd() / 'ZXCalculus',
    Path.cwd() / 'notebooks' / 'ZXCalculus',
    Path.cwd().parent / 'notebooks' / 'ZXCalculus',
]
zx_dir = next((candidate for candidate in zx_candidates if candidate.is_dir()), None)
if zx_dir is None:
    raise FileNotFoundError('No se encontró el directorio ZXCalculus desde el directorio actual')

base_dir = zx_dir / 'algorithms_base'
qasm_dir = zx_dir / 'algorithms_qasm'


def normalized_graph_name(path):
    return re.sub(r'_+', '_', path.stem).casefold()


def algorithm_order(path):
    stem = path.stem.casefold()
    is_popular = stem.startswith('popular_')
    name = stem.removeprefix('popular_') if is_popular else stem
    match = re.match(r'(\d+)', name)
    number = int(match.group(1)) if match else float('inf')
    return (is_popular, number, name)


def index_graphs(directory):
    paths = sorted(directory.glob('*.json'))
    if not paths:
        raise FileNotFoundError(f'No hay grafos JSON en {directory}')
    indexed = {}
    for path in paths:
        key = normalized_graph_name(path)
        if key in indexed:
            raise ValueError(f'Nombres ambiguos en {directory}: {indexed[key].name} y {path.name}')
        indexed[key] = path
    return indexed


base_graphs = index_graphs(base_dir)
qasm_graphs = index_graphs(qasm_dir)
missing_qasm = sorted(base_graphs.keys() - qasm_graphs.keys())
missing_base = sorted(qasm_graphs.keys() - base_graphs.keys())
if missing_qasm or missing_base:
    raise ValueError(f'No coinciden las colecciones. Sin QASM: {missing_qasm}; sin base: {missing_base}')

results = []
ordered_base_paths = sorted(base_graphs.values(), key=algorithm_order)
for base_path in ordered_base_paths:
    key = normalized_graph_name(base_path)
    qasm_path = qasm_graphs[key]
    base_graph = zx.Graph.from_json(base_path.read_text(encoding='utf-8'))
    qasm_graph = zx.Graph.from_json(qasm_path.read_text(encoding='utf-8'))
    base_qubits = base_graph.num_inputs()
    qasm_qubits = qasm_graph.num_inputs()

    base_circuit = None
    qasm_circuit = None
    if base_qubits == qasm_qubits and base_qubits > 10:
        base_circuit = zx.Circuit.from_graph(base_graph)
        qasm_circuit = zx.Circuit.from_graph(qasm_graph)

    zx.simplify.full_reduce(base_graph)
    zx.simplify.full_reduce(qasm_graph)

    if base_qubits != qasm_qubits:
        method = 'sin comparar'
        result = f'NO COMPARABLES (qubits distintos: {base_qubits} vs. {qasm_qubits})'
    elif base_qubits <= 10:
        method = 'compare_tensors (rw-greedy-linear)'
        equivalent = zx.compare_tensors(base_graph, qasm_graph, strategy='rw-greedy-linear')
        result = 'EQUIVALENTES' if equivalent else 'NO EQUIVALENTES'
    else:
        method = 'verify_equality'
        equivalent = base_circuit.verify_equality(qasm_circuit, up_to_global_phase=True)
        result = 'EQUIVALENTES' if equivalent else 'NO DEMOSTRADO'

    results.append({
        'Nombre algoritmo': base_path.stem,
        'Cant. cúbits': base_qubits,
        'Método utilizado': method,
        'Resultado': result,
    })

comparison_table = pd.DataFrame(
    results,
    columns=['Nombre algoritmo', 'Cant. cúbits', 'Método utilizado', 'Resultado'],
)
display(comparison_table)
print('Todos los grafos se redujeron en memoria antes de comparar; los JSON originales no se modificaron.')
print('Nota: NO DEMOSTRADO indica que verify_equality no pudo probar equivalencia; no demuestra inequivalencia.')

,Nombre algoritmo,Cant. cúbits,Método utilizado,Resultado
0,1_Shor,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
1,2_Bernstein-Vazirani,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
2,3_Grover,2,compare_tensors (rw-greedy-linear),EQUIVALENTES
3,4_Deutsch-Jozsa,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
4,5_Simon,6,compare_tensors (rw-greedy-linear),EQUIVALENTES
5,6_TSP,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
6,7_Teleportation,5,compare_tensors (rw-greedy-linear),EQUIVALENTES
7,8_Phase_Estimation,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
8,9_QFT,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
9,10_QAOA,2,compare_tensors (rw-greedy-linear),EQUIVALENTES
10,11_Kickback,2,compare_tensors (rw-greedy-linear),EQUIVALENTES
11,12_Full_Adder,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
12,13_Multicontroled_Gates,5,compare_tensors (rw-greedy-linear),EQUIVALENTES
13,14_Shor_6q,6,compare_tensors (rw-greedy-linear),EQUIVALENTES
14,15_Popurri_6q,6,compare_tensors (rw-greedy-linear),EQUIVALENTES
15,popular_1_adder_n4_vq,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
16,popular_2_adder_n10_vq,10,compare_tensors (rw-greedy-linear),EQUIVALENTES
17,popular_3_adder_n13_vq,13,verify_equality,EQUIVALENTES
18,popular_4_adder_n16_vq,16,verify_equality,EQUIVALENTES
19,popular_5_bv_2_vq,2,compare_tensors (rw-greedy-linear),EQUIVALENTES
20,popular_6_bv_3_vq,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
21,popular_7_bv_4_vq,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
22,popular_8_bv_5_vq,5,compare_tensors (rw-greedy-linear),EQUIVALENTES
23,popular_9_bv_9_vq,9,compare_tensors (rw-greedy-linear),EQUIVALENTES
24,popular_10_bv_14_vq,14,verify_equality,EQUIVALENTES
25,popular_11_dj_indep_4_mqt,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
26,popular_12_dj_indep_5_mqt,5,compare_tensors (rw-greedy-linear),EQUIVALENTES
27,popular_13_dj_indep_7_mqt,7,compare_tensors (rw-greedy-linear),EQUIVALENTES
28,popular_14_dj_indep_14_mqt,14,verify_equality,EQUIVALENTES
29,popular_15_grover-noancilla_3_mqt,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
30,popular_16_grover-noancilla_4_mqt,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
31,popular_17_grover-v-chain_3_mqt,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
32,popular_18_grover-v-chain_4_mqt,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
33,popular_19_grover_3_vq,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
34,popular_20_grover_7_vq,7,compare_tensors (rw-greedy-linear),EQUIVALENTES
35,popular_21_grover_9_vq,9,compare_tensors (rw-greedy-linear),EQUIVALENTES
36,popular_22_kickback_7_vq,7,compare_tensors (rw-greedy-linear),EQUIVALENTES
37,popular_23_pe_2_vq,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
38,popular_24_pe_3_mqt,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
39,popular_25_pe_4_mqt,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
40,popular_26_pe_5_mqt,5,compare_tensors (rw-greedy-linear),EQUIVALENTES
41,popular_27_pe_6_mqt,6,compare_tensors (rw-greedy-linear),EQUIVALENTES
42,popular_28_pe_7_mqt,7,compare_tensors (rw-greedy-linear),EQUIVALENTES
43,popular_29_qft_2_mqt,2,compare_tensors (rw-greedy-linear),EQUIVALENTES
44,popular_30_qft_3_mqt,3,compare_tensors (rw-greedy-linear),EQUIVALENTES
45,popular_31_qft_4_mqt,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
46,popular_32_qft_6_mqt,6,compare_tensors (rw-greedy-linear),EQUIVALENTES
47,popular_33_qft_7_vq,7,compare_tensors (rw-greedy-linear),EQUIVALENTES
48,popular_34_shor_mod15_mqt,5,compare_tensors (rw-greedy-linear),EQUIVALENTES
49,popular_35_shor_mod21_mqt,8,compare_tensors (rw-greedy-linear),EQUIVALENTES
50,popular_36_simon_vq,6,compare_tensors (rw-greedy-linear),EQUIVALENTES
51,popular_37_tsp_indep_4_mqt,4,compare_tensors (rw-greedy-linear),EQUIVALENTES
52,popular_38_tsp_indep_5_mqt,5,compare_tensors (rw-greedy-linear),EQUIVALENTES

Todos los grafos se redujeron en memoria antes de comparar; los JSON originales no se modificaron.
Nota: NO DEMOSTRADO indica que verify_equality no pudo probar equivalencia; no demuestra inequivalencia.

### Generación de imágenes (grafos) asociados a los algoritmos base

Toma cada algoritmo presente en el directorio /algorithms_base y genera un .svg para comprobar la reducción.

In [ ]:
import os
import re
import warnings
from pathlib import Path

import matplotlib
matplotlib.use('Agg', force=True)
import matplotlib.pyplot as plt
import pyzx as zx
from IPython.display import Markdown, display

zx.settings.drawing_backend = 'matplotlib'

zx_candidates = [
    Path.cwd() / 'ZXCalculus',
    Path.cwd() / 'notebooks' / 'ZXCalculus',
    Path.cwd().parent / 'notebooks' / 'ZXCalculus',
]
zx_dir = next((candidate for candidate in zx_candidates if candidate.is_dir()), None)
if zx_dir is None:
    raise FileNotFoundError('No se encontró el directorio ZXCalculus desde el directorio actual')

notebook_candidates = [Path.cwd(), Path.cwd() / 'notebooks', Path.cwd().parent / 'notebooks']
notebook_dir = next(
    (
        candidate
        for candidate in notebook_candidates
        if (candidate / 'input' / 'algorithms.json').is_file()
        and (candidate / 'input' / 'popular_algorithms.json').is_file()
    ),
    None,
)
if notebook_dir is None:
    raise FileNotFoundError('No se encontraron los JSON de algoritmos dentro de input')

base_dir = zx_dir / 'algorithms_base'
output_dir = zx_dir / 'graphs'
graph_paths = list(base_dir.glob('*.json'))
if not graph_paths:
    raise FileNotFoundError(f'No hay grafos JSON en {base_dir}')


def graph_order(path):
    stem = path.stem.casefold()
    is_popular = stem.startswith('popular_')
    name = stem.removeprefix('popular_') if is_popular else stem
    match = re.match(r'(\d+)', name)
    number = int(match.group(1)) if match else float('inf')
    return is_popular, number, name


def markdown_escape(value):
    return str(value).replace('|', '\\|').replace('\n', ' ')


output_dir.mkdir(parents=True, exist_ok=True)
ordered_graph_paths = sorted(graph_paths, key=graph_order)
image_results = []
failed_count = 0

with warnings.catch_warnings():
    warnings.filterwarnings('ignore', message='FigureCanvasAgg is non-interactive')
    for index, graph_path in enumerate(ordered_graph_paths, start=1):
        graph = zx.Graph.from_json(graph_path.read_text(encoding='utf-8'))
        n_qubits = graph.num_inputs()
        vertices_before = graph.num_vertices()
        reduced_graph = graph.copy()
        figure = None
        image_path = output_dir / f'{graph_path.stem}.svg'

        try:
            zx.simplify.full_reduce(reduced_graph)
            vertices_after = reduced_graph.num_vertices()
            figure_width = max(12, min(24, vertices_after / 70))
            figure_height = max(5, min(12, n_qubits * 0.5))
            figure = zx.draw(reduced_graph, labels=True, figsize=(figure_width, figure_height))
            figure.savefig(image_path, format='svg')
            status = 'Generado'
        except Exception as exc:
            failed_count += 1
            vertices_after = reduced_graph.num_vertices()
            status = f'Error: {type(exc).__name__}'
        finally:
            if figure is not None:
                plt.close(figure)

        relative_path = Path(os.path.relpath(image_path, start=notebook_dir)).as_posix()
        image_reference = f'[Abrir SVG]({relative_path})' if image_path.is_file() else '-'
        image_results.append({
            'Nombre algoritmo': graph_path.stem,
            'Cúbits': n_qubits,
            'Vértices (antes → después)': f'{vertices_before} → {vertices_after}',
            'Referencia al grafo': image_reference,
            'Resultado': status,
        })

headers = ['Nombre algoritmo', 'Cúbits', 'Vértices (antes → después)', 'Referencia al grafo', 'Resultado']
markdown_rows = [
    '| ' + ' | '.join(headers) + ' |',
    '| ' + ' | '.join('---' for _ in headers) + ' |',
]
for row in image_results:
    cells = [
        markdown_escape(row['Nombre algoritmo']),
        str(row['Cúbits']),
        row['Vértices (antes → después)'],
        row['Referencia al grafo'],
        markdown_escape(row['Resultado']),
    ]
    markdown_rows.append('| ' + ' | '.join(cells) + ' |')

display(Markdown('\n'.join(markdown_rows)))
print(f'\nSVG generados: {len(image_results) - failed_count}/{len(ordered_graph_paths)}; errores: {failed_count}.')
print(f'Archivos guardados en: {output_dir.resolve()}')

| Nombre algoritmo | Cúbits | Vértices (antes → después) | Referencia al grafo | Resultado |
| --- | --- | --- | --- | --- |
| 1_Shor | 4 | 296 → 11 | [Abrir SVG](ZXCalculus/graphs/1_Shor.svg) | Generado |
| 2_Bernstein-Vazirani | 4 | 129 → 14 | [Abrir SVG](ZXCalculus/graphs/2_Bernstein-Vazirani.svg) | Generado |
| 3_Grover | 2 | 66 → 8 | [Abrir SVG](ZXCalculus/graphs/3_Grover.svg) | Generado |
| 4_Deutsch-Jozsa | 4 | 149 → 14 | [Abrir SVG](ZXCalculus/graphs/4_Deutsch-Jozsa.svg) | Generado |
| 5_Simon | 6 | 177 → 19 | [Abrir SVG](ZXCalculus/graphs/5_Simon.svg) | Generado |
| 6_TSP | 3 | 80 → 11 | [Abrir SVG](ZXCalculus/graphs/6_TSP.svg) | Generado |
| 7_Teleportation | 5 | 125 → 15 | [Abrir SVG](ZXCalculus/graphs/7_Teleportation.svg) | Generado |
| 8_Phase_Estimation | 4 | 239 → 28 | [Abrir SVG](ZXCalculus/graphs/8_Phase_Estimation.svg) | Generado |
| 9_QFT | 3 | 103 → 14 | [Abrir SVG](ZXCalculus/graphs/9_QFT.svg) | Generado |
| 10_QAOA | 2 | 58 → 4 | [Abrir SVG](ZXCalculus/graphs/10_QAOA.svg) | Generado |
| 11_Kickback | 2 | 56 → 7 | [Abrir SVG](ZXCalculus/graphs/11_Kickback.svg) | Generado |
| 12_Full_Adder | 4 | 326 → 54 | [Abrir SVG](ZXCalculus/graphs/12_Full_Adder.svg) | Generado |
| 13_Multicontroled_Gates | 5 | 1013 → 137 | [Abrir SVG](ZXCalculus/graphs/13_Multicontroled_Gates.svg) | Generado |
| 14_Shor_6q | 6 | 379 → 17 | [Abrir SVG](ZXCalculus/graphs/14_Shor_6q.svg) | Generado |
| 15_Popurri_6q | 6 | 4356 → 622 | [Abrir SVG](ZXCalculus/graphs/15_Popurri_6q.svg) | Generado |
| popular_1_adder_n4_vq | 4 | 284 → 54 | [Abrir SVG](ZXCalculus/graphs/popular_1_adder_n4_vq.svg) | Generado |
| popular_2_adder_n10_vq | 10 | 848 → 156 | [Abrir SVG](ZXCalculus/graphs/popular_2_adder_n10_vq.svg) | Generado |
| popular_3_adder_n13_vq | 13 | 1130 → 207 | [Abrir SVG](ZXCalculus/graphs/popular_3_adder_n13_vq.svg) | Generado |
| popular_4_adder_n16_vq | 16 | 1412 → 258 | [Abrir SVG](ZXCalculus/graphs/popular_4_adder_n16_vq.svg) | Generado |
| popular_5_bv_2_vq | 2 | 56 → 7 | [Abrir SVG](ZXCalculus/graphs/popular_5_bv_2_vq.svg) | Generado |
| popular_6_bv_3_vq | 3 | 95 → 11 | [Abrir SVG](ZXCalculus/graphs/popular_6_bv_3_vq.svg) | Generado |
| popular_7_bv_4_vq | 4 | 134 → 14 | [Abrir SVG](ZXCalculus/graphs/popular_7_bv_4_vq.svg) | Generado |
| popular_8_bv_5_vq | 5 | 173 → 16 | [Abrir SVG](ZXCalculus/graphs/popular_8_bv_5_vq.svg) | Generado |
| popular_9_bv_9_vq | 9 | 329 → 29 | [Abrir SVG](ZXCalculus/graphs/popular_9_bv_9_vq.svg) | Generado |
| popular_10_bv_14_vq | 14 | 524 → 44 | [Abrir SVG](ZXCalculus/graphs/popular_10_bv_14_vq.svg) | Generado |
| popular_11_dj_indep_4_mqt | 4 | 120 → 14 | [Abrir SVG](ZXCalculus/graphs/popular_11_dj_indep_4_mqt.svg) | Generado |
| popular_12_dj_indep_5_mqt | 5 | 157 → 17 | [Abrir SVG](ZXCalculus/graphs/popular_12_dj_indep_5_mqt.svg) | Generado |
| popular_13_dj_indep_7_mqt | 7 | 233 → 23 | [Abrir SVG](ZXCalculus/graphs/popular_13_dj_indep_7_mqt.svg) | Generado |
| popular_14_dj_indep_14_mqt | 14 | 496 → 43 | [Abrir SVG](ZXCalculus/graphs/popular_14_dj_indep_14_mqt.svg) | Generado |
| popular_15_grover-noancilla_3_mqt | 3 | 171 → 22 | [Abrir SVG](ZXCalculus/graphs/popular_15_grover-noancilla_3_mqt.svg) | Generado |
| popular_16_grover-noancilla_4_mqt | 4 | 880 → 113 | [Abrir SVG](ZXCalculus/graphs/popular_16_grover-noancilla_4_mqt.svg) | Generado |
| popular_17_grover-v-chain_3_mqt | 3 | 171 → 22 | [Abrir SVG](ZXCalculus/graphs/popular_17_grover-v-chain_3_mqt.svg) | Generado |
| popular_18_grover-v-chain_4_mqt | 4 | 880 → 113 | [Abrir SVG](ZXCalculus/graphs/popular_18_grover-v-chain_4_mqt.svg) | Generado |
| popular_19_grover_3_vq | 3 | 214 → 37 | [Abrir SVG](ZXCalculus/graphs/popular_19_grover_3_vq.svg) | Generado |
| popular_20_grover_7_vq | 7 | 1022 → 152 | [Abrir SVG](ZXCalculus/graphs/popular_20_grover_7_vq.svg) | Generado |
| popular_21_grover_9_vq | 9 | 1495 → 207 | [Abrir SVG](ZXCalculus/graphs/popular_21_grover_9_vq.svg) | Generado |
| popular_22_kickback_7_vq | 7 | 188 → 28 | [Abrir SVG](ZXCalculus/graphs/popular_22_kickback_7_vq.svg) | Generado |
| popular_23_pe_2_vq | 3 | 83 → 17 | [Abrir SVG](ZXCalculus/graphs/popular_23_pe_2_vq.svg) | Generado |
| popular_24_pe_3_mqt | 3 | 75 → 14 | [Abrir SVG](ZXCalculus/graphs/popular_24_pe_3_mqt.svg) | Generado |
| popular_25_pe_4_mqt | 4 | 125 → 20 | [Abrir SVG](ZXCalculus/graphs/popular_25_pe_4_mqt.svg) | Generado |
| popular_26_pe_5_mqt | 5 | 257 → 42 | [Abrir SVG](ZXCalculus/graphs/popular_26_pe_5_mqt.svg) | Generado |
| popular_27_pe_6_mqt | 6 | 345 → 56 | [Abrir SVG](ZXCalculus/graphs/popular_27_pe_6_mqt.svg) | Generado |
| popular_28_pe_7_mqt | 7 | 458 → 72 | [Abrir SVG](ZXCalculus/graphs/popular_28_pe_7_mqt.svg) | Generado |
| popular_29_qft_2_mqt | 2 | 39 → 10 | [Abrir SVG](ZXCalculus/graphs/popular_29_qft_2_mqt.svg) | Generado |
| popular_30_qft_3_mqt | 3 | 84 → 18 | [Abrir SVG](ZXCalculus/graphs/popular_30_qft_3_mqt.svg) | Generado |
| popular_31_qft_4_mqt | 4 | 154 → 32 | [Abrir SVG](ZXCalculus/graphs/popular_31_qft_4_mqt.svg) | Generado |
| popular_32_qft_6_mqt | 6 | 345 → 58 | [Abrir SVG](ZXCalculus/graphs/popular_32_qft_6_mqt.svg) | Generado |
| popular_33_qft_7_vq | 7 | 448 → 79 | [Abrir SVG](ZXCalculus/graphs/popular_33_qft_7_vq.svg) | Generado |
| popular_34_shor_mod15_mqt | 5 | 288 → 11 | [Abrir SVG](ZXCalculus/graphs/popular_34_shor_mod15_mqt.svg) | Generado |
| popular_35_shor_mod21_mqt | 8 | 245 → 28 | [Abrir SVG](ZXCalculus/graphs/popular_35_shor_mod21_mqt.svg) | Generado |
| popular_36_simon_vq | 6 | 165 → 20 | [Abrir SVG](ZXCalculus/graphs/popular_36_simon_vq.svg) | Generado |
| popular_37_tsp_indep_4_mqt | 4 | 394 → 40 | [Abrir SVG](ZXCalculus/graphs/popular_37_tsp_indep_4_mqt.svg) | Generado |
| popular_38_tsp_indep_5_mqt | 5 | 798 → 109 | [Abrir SVG](ZXCalculus/graphs/popular_38_tsp_indep_5_mqt.svg) | Generado |

SVG generados: 53/53; errores: 0.
Archivos guardados en: C:\Users\JoséManuel Suarez\desarrollo\QTransLIFIA\notebooks\ZXCalculus\graphs

## Generación de circuitos Qiskit

A partir de los circuitos en OpenQASM generamos los circuitos Qiskit. Los scripts se guardan en `output/migrated_circuits/qiskit`.

In [15]:
from pathlib import Path
import re
import pandas as pd
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, qasm3

base_dir = Path.cwd()
if not (base_dir / "algorithms_qasm").is_dir() and (base_dir / "notebooks" / "algorithms_qasm").is_dir():
    base_dir = base_dir / "notebooks"

qasm_dir = base_dir / "algorithms_qasm"
output_dir = base_dir / "output" / "migrated_circuits" / "qiskit"
output_dir.mkdir(parents=True, exist_ok=True)
qasm_files = [path for path in qasm_dir.iterdir() if path.is_file() and path.suffix.lower() == ".txt"]
if not qasm_files:
    raise FileNotFoundError(f"No se encontraron archivos OpenQASM .txt en {qasm_dir}")

gate_classes = {"h": "HGate", "swap": "SwapGate", "x": "XGate", "y": "YGate", "z": "ZGate"}
qiskit_circuits = {}
summary_rows = []

for qasm_path in qasm_files:
    parsed_circuit = qasm3.loads(qasm_path.read_text(encoding="utf-8"))
    register_variables = []
    register_declarations = []
    qubit_references = {}
    clbit_references = {}

    for register in parsed_circuit.qregs:
        variable = f"qreg_{re.sub(r'\\W', '_', register.name)}"
        register_variables.append(variable)
        register_declarations.append(f"{variable} = QuantumRegister({len(register)}, {register.name!r})")
        for index, bit in enumerate(register):
            qubit_references[bit] = f"{variable}[{index}]"

    for register in parsed_circuit.cregs:
        variable = f"creg_{re.sub(r'\\W', '_', register.name)}"
        register_variables.append(variable)
        register_declarations.append(f"{variable} = ClassicalRegister({len(register)}, {register.name!r})")
        for index, bit in enumerate(register):
            clbit_references[bit] = f"{variable}[{index}]"

    gate_imports = set()
    instructions = []
    for item in parsed_circuit.data:
        operation = item.operation
        qubits = [qubit_references[bit] for bit in item.qubits]
        clbits = [clbit_references[bit] for bit in item.clbits]
        parameters = [repr(parameter) for parameter in operation.params]

        if operation.name == "mcx":
            controls = qubits[:-1]
            control_state = operation.ctrl_state
            control_arg = f", ctrl_state={control_state}" if control_state != (1 << len(controls)) - 1 else ""
            instructions.append(f"circuit.mcx([{', '.join(controls)}], {qubits[-1]}{control_arg})")
        elif hasattr(parsed_circuit, operation.name):
            arguments = parameters + qubits + clbits
            instructions.append(f"circuit.{operation.name}({', '.join(arguments)})")
        else:
            base_name = operation.base_gate.name
            if base_name not in gate_classes:
                raise ValueError(f"Puerta controlada no soportada: {operation.name}")
            gate_class = gate_classes[base_name]
            gate_imports.add(gate_class)
            control_state = operation.ctrl_state
            control_count = operation.num_ctrl_qubits
            control_args = f", ctrl_state={control_state}" if control_state != (1 << control_count) - 1 else ""
            gate_expression = f"{gate_class}().control({control_count}{control_args})"
            instructions.append(f"circuit.append({gate_expression}, [{', '.join(qubits)}])")

    imports = [
        "# Importación de paquetes requeridos",
        "from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister",
    ]
    if gate_imports:
        imports.append(f"from qiskit.circuit.library import {', '.join(sorted(gate_imports))}")

    python_lines = imports + ["", "# Generación de registros cuánticos y clásicos"] + register_declarations
    python_lines.extend(["", "# Creación del circuito cuántico"])
    python_lines.append(f"circuit = QuantumCircuit({', '.join(register_variables)})")
    python_lines.extend([""] + instructions)
    python_source = "\n".join(python_lines) + "\n"

    output_path = output_dir / f"{qasm_path.stem}.py"
    output_path.write_text(python_source, encoding="utf-8")
    namespace = {}
    exec(compile(python_source, str(output_path), "exec"), namespace)
    circuit = namespace["circuit"]
    qiskit_circuits[qasm_path.stem] = circuit

    summary_rows.append(
        {
            "Nombre algoritmo": f"{qasm_path.stem}.py",
            "# cubits": circuit.num_qubits,
            "# líneas": len(python_lines),
        }
    )

summary = pd.DataFrame(summary_rows, columns=["Nombre algoritmo", "# cubits", "# líneas"])
display(summary)
print(f"Circuitos Qiskit generados: {len(qiskit_circuits)} en {output_dir}")

                         Nombre algoritmo  # cubits  # líneas
0                             10__QAOA.py         2        14
1                         11__Kickback.py         2        18
2                       12__Full_Adder.py         4        22
3             13__Multicontroled_Gates.py         5        27
4                          14__Shor_6q.py         6        41
5                       15__Popurri_6q.py         6        53
6                              1__Shor.py         4        32
7                2__Bernstein-Vazirani.py         4        24
8                            3__Grover.py         2        19
9                     4__Deutsch-Jozsa.py         4        28
10                            5__Simon.py         6        24
11                              6__TSP.py         3        19
12                    7__Teleportation.py         5        19
13                 8__Phase_Estimation.py         4        31
14                              9__QFT.py         3        21
15                popular_10__bv_14_vq.py        14        65
16          popular_11__dj_indep_4_mqt.py         4        23
17          popular_12__dj_indep_5_mqt.py         5        27
18          popular_13__dj_indep_7_mqt.py         7        35
19         popular_14__dj_indep_14_mqt.py        14        63
20  popular_15__grover-noancilla_3_mqt.py         3        26
21  popular_16__grover-noancilla_4_mqt.py         4        58
22    popular_17__grover-v-chain_3_mqt.py         3        26
23    popular_18__grover-v-chain_4_mqt.py         4        58
24             popular_19__grover_3_vq.py         3        29
25              popular_1__adder_n4_vq.py         4        18
26             popular_20__grover_7_vq.py         7        49
27             popular_21__grover_9_vq.py         9        60
28           popular_22__kickback_7_vq.py         7        20
29                 popular_23__pe_2_vq.py         3        20
30                popular_24__pe_3_mqt.py         3        20
31                popular_25__pe_4_mqt.py         4        25
32                popular_26__pe_5_mqt.py         5        35
33                popular_27__pe_6_mqt.py         6        42
34                popular_28__pe_7_mqt.py         7        51
35               popular_29__qft_2_mqt.py         2        16
36             popular_2__adder_n10_vq.py        10        22
37               popular_30__qft_3_mqt.py         3        20
38               popular_31__qft_4_mqt.py         4        26
39               popular_32__qft_6_mqt.py         6        40
40                popular_33__qft_7_vq.py         7        45
41          popular_34__shor_mod15_mqt.py         5        30
42          popular_35__shor_mod21_mqt.py         8        29
43                popular_36__simon_vq.py         6        26
44         popular_37__tsp_indep_4_mqt.py         4        53
45         popular_38__tsp_indep_5_mqt.py         5        39
46             popular_3__adder_n13_vq.py        13        39
47             popular_4__adder_n16_vq.py        16        46
48                  popular_5__bv_2_vq.py         2        16
49                  popular_6__bv_3_vq.py         3        22
50                  popular_7__bv_4_vq.py         4        26
51                  popular_8__bv_5_vq.py         5        30
52                  popular_9__bv_9_vq.py         9        46

Circuitos Qiskit generados: 53 en c:\Users\PC\desarrollo\QTransLIFIA\notebooks\output\migrated_circuits\qiskit

## Generación de algoritmos migrados a AWS Braket

Convierte cada archivo OpenQASM 3.0 de `algorithms_qasm` en código Python nativo de AWS Braket y lo guarda en `output/migrated_circuits/aws_braket`.

El notebook requiere Qiskit y `qiskit-qasm3-import` para leer las fuentes. Para ejecutar los scripts generados, instala `amazon-braket-sdk` (`python -m pip install amazon-braket-sdk`).

In [16]:
from pathlib import Path
import pandas as pd
from qiskit import qasm3

base_dir = Path.cwd()
if not (base_dir / "algorithms_qasm").is_dir() and (base_dir / "notebooks" / "algorithms_qasm").is_dir():
    base_dir = base_dir / "notebooks"

qasm_dir = base_dir / "algorithms_qasm"
output_dir = base_dir / "output" / "migrated_circuits" / "aws_braket"
output_dir.mkdir(parents=True, exist_ok=True)
qasm_files = [path for path in qasm_dir.iterdir() if path.is_file() and path.suffix.lower() == ".txt"]
if not qasm_files:
    raise FileNotFoundError(f"No se encontraron archivos OpenQASM .txt en {qasm_dir}")


def braket_instruction(item, parsed_circuit):
    operation = item.operation
    qubits = [parsed_circuit.find_bit(bit).index for bit in item.qubits]
    parameters = [repr(parameter) for parameter in operation.params]

    if operation.name == "measure":
        return f"circuit.measure([{qubits[0]}])"

    if hasattr(operation, "base_gate"):
        control_count = operation.num_ctrl_qubits
        controls = qubits[:control_count]
        targets = qubits[control_count:]
        base_name = operation.base_gate.name
        control_state = operation.ctrl_state
        control_args = f", control_state={control_state}" if control_state != (1 << control_count) - 1 else ""

        if base_name == "p":
            return f"circuit.cphaseshift({controls!r}, {targets[0]}, {parameters[0]})"
        if base_name == "swap":
            return f"circuit.swap({targets[0]}, {targets[1]}, control={controls!r}{control_args})"
        if base_name in {"h", "rx", "ry", "rz", "x", "y", "z"}:
            arguments = [str(targets[0])] + parameters + [f"control={controls!r}"]
            if control_state != (1 << control_count) - 1:
                arguments.append(f"control_state={control_state}")
            return f"circuit.{base_name}({', '.join(arguments)})"
        raise ValueError(f"Puerta controlada no soportada por el generador: {operation.name}")

    if operation.name == "swap":
        return f"circuit.swap({qubits[0]}, {qubits[1]})"
    if operation.name in {"h", "rx", "ry", "rz", "x", "y", "z"}:
        arguments = [str(qubits[0])] + parameters
        return f"circuit.{operation.name}({', '.join(arguments)})"

    raise ValueError(f"Puerta OpenQASM no soportada por el generador: {operation.name}")


summary_rows = []
for qasm_path in qasm_files:
    qasm_source = qasm_path.read_text(encoding="utf-8")
    parsed_circuit = qasm3.loads(qasm_source)
    instructions = [braket_instruction(item, parsed_circuit) for item in parsed_circuit.data]

    python_lines = [
        "# Importación de paquetes requeridos",
        "from braket.circuits import Circuit",
        "",
        "# Creación del circuito AWS Braket",
        "circuit = Circuit()",
        "",
        "# Puertas y mediciones migradas desde OpenQASM 3.0",
        *instructions,
    ]
    python_source = "\n".join(python_lines) + "\n"
    output_path = output_dir / f"{qasm_path.stem}.py"
    compile(python_source, str(output_path), "exec")
    output_path.write_text(python_source, encoding="utf-8")

    summary_rows.append(
        {
            "Nombre algoritmo": f"{qasm_path.stem}.py",
            "# cubits": parsed_circuit.num_qubits,
            "# líneas": len(python_lines),
        }
    )

summary_aws = pd.DataFrame(summary_rows, columns=["Nombre algoritmo", "# cubits", "# líneas"])
display(summary_aws)
print(f"Circuitos AWS Braket generados: {len(summary_aws)} en {output_dir}")

                         Nombre algoritmo  # cubits  # líneas
0                             10__QAOA.py         2        11
1                         11__Kickback.py         2        15
2                       12__Full_Adder.py         4        19
3             13__Multicontroled_Gates.py         5        23
4                          14__Shor_6q.py         6        38
5                       15__Popurri_6q.py         6        49
6                              1__Shor.py         4        29
7                2__Bernstein-Vazirani.py         4        21
8                            3__Grover.py         2        16
9                     4__Deutsch-Jozsa.py         4        25
10                            5__Simon.py         6        21
11                              6__TSP.py         3        16
12                    7__Teleportation.py         5        16
13                 8__Phase_Estimation.py         4        28
14                              9__QFT.py         3        18
15                popular_10__bv_14_vq.py        14        62
16          popular_11__dj_indep_4_mqt.py         4        20
17          popular_12__dj_indep_5_mqt.py         5        24
18          popular_13__dj_indep_7_mqt.py         7        32
19         popular_14__dj_indep_14_mqt.py        14        60
20  popular_15__grover-noancilla_3_mqt.py         3        23
21  popular_16__grover-noancilla_4_mqt.py         4        55
22    popular_17__grover-v-chain_3_mqt.py         3        23
23    popular_18__grover-v-chain_4_mqt.py         4        55
24             popular_19__grover_3_vq.py         3        26
25              popular_1__adder_n4_vq.py         4        15
26             popular_20__grover_7_vq.py         7        46
27             popular_21__grover_9_vq.py         9        57
28           popular_22__kickback_7_vq.py         7        17
29                 popular_23__pe_2_vq.py         3        17
30                popular_24__pe_3_mqt.py         3        17
31                popular_25__pe_4_mqt.py         4        22
32                popular_26__pe_5_mqt.py         5        32
33                popular_27__pe_6_mqt.py         6        39
34                popular_28__pe_7_mqt.py         7        48
35               popular_29__qft_2_mqt.py         2        13
36             popular_2__adder_n10_vq.py        10        19
37               popular_30__qft_3_mqt.py         3        17
38               popular_31__qft_4_mqt.py         4        23
39               popular_32__qft_6_mqt.py         6        37
40                popular_33__qft_7_vq.py         7        42
41          popular_34__shor_mod15_mqt.py         5        27
42          popular_35__shor_mod21_mqt.py         8        26
43                popular_36__simon_vq.py         6        23
44         popular_37__tsp_indep_4_mqt.py         4        50
45         popular_38__tsp_indep_5_mqt.py         5        36
46             popular_3__adder_n13_vq.py        13        36
47             popular_4__adder_n16_vq.py        16        43
48                  popular_5__bv_2_vq.py         2        13
49                  popular_6__bv_3_vq.py         3        19
50                  popular_7__bv_4_vq.py         4        23
51                  popular_8__bv_5_vq.py         5        27
52                  popular_9__bv_9_vq.py         9        43

Circuitos AWS Braket generados: 53 en c:\Users\PC\desarrollo\QTransLIFIA\notebooks\output\migrated_circuits\aws_braket

## Generación de algoritmos migrados a PennyLane

Convierte cada fuente OpenQASM 3.0 en un script Python con un QNode de PennyLane. Los archivos se guardan en `output/migrated_circuits/pennylane`; se requiere Qiskit y `qiskit-qasm3-import` para leer las fuentes, y PennyLane (`python -m pip install pennylane`) para ejecutar los scripts.

Los QNodes con mediciones devuelven muestras en el orden de los bits clásicos medidos. Los circuitos sin mediciones devuelven el estado cuántico.

In [18]:
from pathlib import Path
import pandas as pd
from qiskit import qasm3

base_dir = Path.cwd()
if not (base_dir / "algorithms_qasm").is_dir() and (base_dir / "notebooks" / "algorithms_qasm").is_dir():
    base_dir = base_dir / "notebooks"

qasm_dir = base_dir / "algorithms_qasm"
output_dir = base_dir / "output" / "migrated_circuits" / "pennylane"
output_dir.mkdir(parents=True, exist_ok=True)
qasm_files = [path for path in qasm_dir.iterdir() if path.is_file() and path.suffix.lower() == ".txt"]
if not qasm_files:
    raise FileNotFoundError(f"No se encontraron archivos OpenQASM .txt en {qasm_dir}")

pennylane_gates = {
    "h": "Hadamard",
    "p": "PhaseShift",
    "rx": "RX",
    "ry": "RY",
    "rz": "RZ",
    "swap": "SWAP",
    "x": "PauliX",
    "y": "PauliY",
    "z": "PauliZ",
}
summary_rows = []

for qasm_path in qasm_files:
    parsed_circuit = qasm3.loads(qasm_path.read_text(encoding="utf-8"))
    instructions = []
    measurement_variables = {}
    measurement_count = 0

    for item in parsed_circuit.data:
        operation = item.operation
        qubits = [parsed_circuit.find_bit(bit).index for bit in item.qubits]
        parameters = [repr(parameter) for parameter in operation.params]

        if operation.name == "measure":
            classical_index = parsed_circuit.find_bit(item.clbits[0]).index
            variable = f"measurement_{classical_index}_{measurement_count}"
            measurement_count += 1
            measurement_variables[classical_index] = variable
            instructions.append(f"{variable} = qml.measure(wires={qubits[0]})")
            continue

        if hasattr(operation, "base_gate"):
            control_count = operation.num_ctrl_qubits
            controls = qubits[:control_count]
            targets = qubits[control_count:]
            base_name = operation.base_gate.name
            gate_name = pennylane_gates.get(base_name)
            if gate_name is None:
                raise ValueError(f"Puerta controlada no soportada: {operation.name}")

            control_values = ""
            if operation.ctrl_state != (1 << control_count) - 1:
                values = tuple(int(value) for value in f"{operation.ctrl_state:0{control_count}b}")
                control_values = f", control_values={values!r}"
            controlled_gate = f"qml.ctrl(qml.{gate_name}, control={controls!r}{control_values})"

            if base_name == "swap":
                gate_arguments = [f"wires={targets!r}"]
            else:
                gate_arguments = parameters + [f"wires={targets[0]}"]
            instructions.append(f"{controlled_gate}({', '.join(gate_arguments)})")
            continue

        gate_name = pennylane_gates.get(operation.name)
        if gate_name is None:
            raise ValueError(f"Puerta OpenQASM no soportada: {operation.name}")
        if operation.name == "swap":
            gate_arguments = [f"wires={qubits!r}"]
        else:
            gate_arguments = parameters + [f"wires={qubits[0]}"]
        instructions.append(f"qml.{gate_name}({', '.join(gate_arguments)})")

    measured_classical_bits = sorted(measurement_variables)
    shots = 1000 if measured_classical_bits else None
    python_lines = [
        "# Importación de paquetes requeridos",
        "import pennylane as qml",
        "",
        f"device = qml.device('default.qubit', wires={parsed_circuit.num_qubits}, shots={shots!r})",
        "",
        "@qml.qnode(device)",
        "def circuit():",
        *[f"    {instruction}" for instruction in instructions],
    ]

    if measured_classical_bits:
        python_lines.append("    return (")
        python_lines.extend(
            f"        qml.sample({measurement_variables[classical_index]}),"
            for classical_index in measured_classical_bits
        )
        python_lines.append("    )")
    else:
        python_lines.append("    return qml.state()")

    python_source = "\n".join(python_lines) + "\n"
    output_path = output_dir / f"{qasm_path.stem}.py"
    compile(python_source, str(output_path), "exec")
    output_path.write_text(python_source, encoding="utf-8")

    summary_rows.append(
        {
            "Nombre algoritmo": f"{qasm_path.stem}.py",
            "# cubits": parsed_circuit.num_qubits,
            "# líneas": len(python_lines),
        }
    )

summary_pennylane = pd.DataFrame(summary_rows, columns=["Nombre algoritmo", "# cubits", "# líneas"])
display(summary_pennylane)
print(f"Circuitos PennyLane generados: {len(summary_pennylane)} en {output_dir}")

                         Nombre algoritmo  # cubits  # líneas
0                             10__QAOA.py         2        15
1                         11__Kickback.py         2        19
2                       12__Full_Adder.py         4        25
3             13__Multicontroled_Gates.py         5        30
4                          14__Shor_6q.py         6        46
5                       15__Popurri_6q.py         6        50
6                              1__Shor.py         4        35
7                2__Bernstein-Vazirani.py         4        26
8                            3__Grover.py         2        19
9                     4__Deutsch-Jozsa.py         4        30
10                            5__Simon.py         6        26
11                              6__TSP.py         3        21
12                    7__Teleportation.py         5        20
13                 8__Phase_Estimation.py         4        33
14                              9__QFT.py         3        19
15                popular_10__bv_14_vq.py        14        77
16          popular_11__dj_indep_4_mqt.py         4        25
17          popular_12__dj_indep_5_mqt.py         5        30
18          popular_13__dj_indep_7_mqt.py         7        40
19         popular_14__dj_indep_14_mqt.py        14        75
20  popular_15__grover-noancilla_3_mqt.py         3        28
21  popular_16__grover-noancilla_4_mqt.py         4        61
22    popular_17__grover-v-chain_3_mqt.py         3        28
23    popular_18__grover-v-chain_4_mqt.py         4        61
24             popular_19__grover_3_vq.py         3        31
25              popular_1__adder_n4_vq.py         4        21
26             popular_20__grover_7_vq.py         7        55
27             popular_21__grover_9_vq.py         9        68
28           popular_22__kickback_7_vq.py         7        20
29                 popular_23__pe_2_vq.py         3        22
30                popular_24__pe_3_mqt.py         3        21
31                popular_25__pe_4_mqt.py         4        27
32                popular_26__pe_5_mqt.py         5        38
33                popular_27__pe_6_mqt.py         6        46
34                popular_28__pe_7_mqt.py         7        56
35               popular_29__qft_2_mqt.py         2        17
36             popular_2__adder_n10_vq.py        10        20
37               popular_30__qft_3_mqt.py         3        22
38               popular_31__qft_4_mqt.py         4        29
39               popular_32__qft_6_mqt.py         6        45
40                popular_33__qft_7_vq.py         7        51
41          popular_34__shor_mod15_mqt.py         5        33
42          popular_35__shor_mod21_mqt.py         8        32
43                popular_36__simon_vq.py         6        28
44         popular_37__tsp_indep_4_mqt.py         4        56
45         popular_38__tsp_indep_5_mqt.py         5        41
46             popular_3__adder_n13_vq.py        13        51
47             popular_4__adder_n16_vq.py        16        61
48                  popular_5__bv_2_vq.py         2        14
49                  popular_6__bv_3_vq.py         3        24
50                  popular_7__bv_4_vq.py         4        29
51                  popular_8__bv_5_vq.py         5        34
52                  popular_9__bv_9_vq.py         9        54

Circuitos PennyLane generados: 53 en c:\Users\PC\desarrollo\QTransLIFIA\notebooks\output\migrated_circuits\pennylane